import React from "react";
import type {Metadata} from "next";
export const metadata: Metadata = {
    title: "Click2Eat | Registro",
    description: "Generated by create next restaurant",
};
export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            {children}
        </>
    );
}